[package]
name = "tauri-plugin-decorum"
version = "1.1.1"
authors = ["Siddharth <siddharth99c@gmail.com>"]
description = "Opnionated window decoration controls for Tauri apps."
edition = "2021"
rust-version = "1.70"
exclude = ["/examples", "/webview-dist", "/webview-src", "/node_modules"]
links = "tauri-plugin-decorum"
license = "MIT"
homepage = "https://github.com/clearlysid/tauri-plugin-decorum"
repository = "https://github.com/clearlysid/tauri-plugin-decorum"

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
serde = { version = "1.0", features = ["derive"] }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.25"
objc = "0.2"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.58", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation"] }

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.18"

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }
